[2023-12-29 00:14:22,251.251] INFO [3069371968] - Shutting down
[2023-12-29 00:14:22,359.359] INFO [3069371968] - Waiting for application shutdown.
[2023-12-29 00:14:22,362.362] INFO [3069371968] - Application shutdown complete.
[2023-12-29 00:14:22,364.364] INFO [3069371968] - Finished server process [6998]
[2023-12-29 00:18:44,277.277] INFO [3070170688] - Started server process [12333]
[2023-12-29 00:18:44,280.280] INFO [3070170688] - Waiting for application startup.
[2023-12-29 00:18:44,284.284] INFO [3070170688] - Application startup complete.
[2023-12-29 00:18:44,320.320] INFO [3070170688] - Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[2023-12-29 00:18:52,834.834] INFO [3070170688] - 192.168.1.74:59433 - "GET /status HTTP/1.1" 200
[2023-12-29 00:19:14,139.139] INFO [3070170688] - 192.168.1.74:59481 - "GET /status HTTP/1.1" 200
[2023-12-29 00:19:15,014.014] INFO [3070170688] - 192.168.1.74:59481 - "GET /status HTTP/1.1" 200
[2023-12-29 00:19:15,760.760] INFO [3070170688] - 192.168.1.74:59481 - "GET /status HTTP/1.1" 200
[2023-12-29 00:19:16,672.672] INFO [3070170688] - 192.168.1.74:59481 - "GET /status HTTP/1.1" 200
[2023-12-29 00:19:17,795.795] INFO [3070170688] - 192.168.1.74:59481 - "GET /status HTTP/1.1" 200
[2023-12-29 00:19:39,710.710] INFO [3070170688] - 192.168.1.74:59474 - "GET /available HTTP/1.1" 200
[2023-12-29 00:20:04,928.928] INFO [3070170688] - Shutting down
[2023-12-29 00:20:05,032.032] INFO [3070170688] - Waiting for application shutdown.
[2023-12-29 00:20:05,035.035] INFO [3070170688] - Application shutdown complete.
[2023-12-29 00:20:05,037.037] INFO [3070170688] - Finished server process [12333]
[2023-12-29 00:20:33,301.301] INFO [3069941312] - Started server process [12483]
[2023-12-29 00:20:33,305.305] INFO [3069941312] - Waiting for application startup.
[2023-12-29 00:20:33,309.309] INFO [3069941312] - Application startup complete.
[2023-12-29 00:20:33,343.343] INFO [3069941312] - Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[2023-12-29 00:20:41,667.667] INFO [3069941312] - 192.168.1.74:59677 - "GET /status HTTP/1.1" 200
[2023-12-29 00:20:48,347.347] INFO [3069941312] - 192.168.1.74:59692 - "GET /status HTTP/1.1" 200
[2023-12-29 00:20:49,444.444] INFO [3069941312] - 192.168.1.74:59692 - "GET /status HTTP/1.1" 200
[2023-12-29 00:21:13,732.732] INFO [3069941312] - 192.168.1.74:59677 - "GET /available HTTP/1.1" 200
[2023-12-29 00:22:04,941.941] INFO [3069941312] - Shutting down
[2023-12-29 00:22:05,044.044] INFO [3069941312] - Waiting for application shutdown.
[2023-12-29 00:22:05,048.048] INFO [3069941312] - Application shutdown complete.
[2023-12-29 00:22:05,049.049] INFO [3069941312] - Finished server process [12483]
[2023-12-29 00:22:44,343.343] INFO [3069896256] - Started server process [12736]
[2023-12-29 00:22:44,348.348] INFO [3069896256] - Waiting for application startup.
[2023-12-29 00:22:44,352.352] INFO [3069896256] - Application startup complete.
[2023-12-29 00:22:44,431.431] INFO [3069896256] - Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[2023-12-29 00:22:55,008.008] INFO [3069896256] - 192.168.1.74:59975 - "GET /status HTTP/1.1" 500
[2023-12-29 00:22:55,011.011] ERROR [3069896256] - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 70, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/dist-packages/starlette/concurrency.py", line 35, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/an63l/app/main.py", line 33, in status
    status = get_status()
  File "/home/an63l/app/main.py", line 87, in get_status
    status = db.search(q.status)
  File "/usr/local/lib/python3.9/dist-packages/tinydb/table.py", line 252, in search
    docs = [
  File "/usr/local/lib/python3.9/dist-packages/tinydb/table.py", line 255, in <listcomp>
    if cond(doc)
  File "/usr/local/lib/python3.9/dist-packages/tinydb/queries.py", line 92, in __call__
    return self._test(value)
  File "/usr/local/lib/python3.9/dist-packages/tinydb/queries.py", line 175, in notest
    raise RuntimeError('Empty query was evaluated')
RuntimeError: Empty query was evaluated
[2023-12-29 00:24:26,123.123] INFO [3069896256] - Shutting down
[2023-12-29 00:24:26,227.227] INFO [3069896256] - Waiting for application shutdown.
[2023-12-29 00:24:26,230.230] INFO [3069896256] - Application shutdown complete.
[2023-12-29 00:24:26,232.232] INFO [3069896256] - Finished server process [12736]
[2023-12-29 00:25:01,596.596] INFO [3069941312] - Started server process [13093]
[2023-12-29 00:25:01,599.599] INFO [3069941312] - Waiting for application startup.
[2023-12-29 00:25:01,603.603] INFO [3069941312] - Application startup complete.
[2023-12-29 00:25:01,638.638] INFO [3069941312] - Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[2023-12-29 00:25:02,156.156] INFO [3069941312] - 192.168.1.74:60266 - "GET /status HTTP/1.1" 500
[2023-12-29 00:25:02,158.158] ERROR [3069941312] - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 70, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/dist-packages/starlette/concurrency.py", line 35, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/an63l/app/main.py", line 33, in status
    status = get_status()
  File "/home/an63l/app/main.py", line 87, in get_status
    status = item.status
AttributeError: 'Document' object has no attribute 'status'
[2023-12-29 00:25:05,243.243] INFO [3069941312] - 192.168.1.74:60274 - "GET /status HTTP/1.1" 500
[2023-12-29 00:25:05,246.246] ERROR [3069941312] - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 70, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/dist-packages/starlette/concurrency.py", line 35, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/an63l/app/main.py", line 33, in status
    status = get_status()
  File "/home/an63l/app/main.py", line 87, in get_status
    status = item.status
AttributeError: 'Document' object has no attribute 'status'
[2023-12-29 00:25:49,442.442] INFO [3069941312] - Shutting down
[2023-12-29 00:25:49,545.545] INFO [3069941312] - Waiting for application shutdown.
[2023-12-29 00:25:49,548.548] INFO [3069941312] - Application shutdown complete.
[2023-12-29 00:25:49,550.550] INFO [3069941312] - Finished server process [13093]
[2023-12-29 00:26:22,407.407] INFO [3070088768] - Started server process [13248]
[2023-12-29 00:26:22,410.410] INFO [3070088768] - Waiting for application startup.
[2023-12-29 00:26:22,414.414] INFO [3070088768] - Application startup complete.
[2023-12-29 00:26:22,448.448] INFO [3070088768] - Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[2023-12-29 00:26:26,452.452] INFO [3070088768] - 192.168.1.74:60456 - "GET /status HTTP/1.1" 200
[2023-12-29 00:28:13,778.778] INFO [3070088768] - 192.168.1.74:60690 - "GET /available HTTP/1.1" 500
[2023-12-29 00:28:13,793.793] ERROR [3070088768] - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 70, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/dist-packages/starlette/concurrency.py", line 35, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/an63l/app/main.py", line 55, in available
    display(concentrating, welcome_framebuffer, "AVAILABLE")
  File "/home/an63l/app/main.py", line 128, in display
    db.update({"status": "WRITING"}, Query().status.exists)
  File "/usr/local/lib/python3.9/dist-packages/tinydb/table.py", line 434, in update
    self._update_table(updater)
  File "/usr/local/lib/python3.9/dist-packages/tinydb/table.py", line 755, in _update_table
    updater(table)
  File "/usr/local/lib/python3.9/dist-packages/tinydb/table.py", line 426, in updater
    if _cond(table[doc_id]):
TypeError: exists() takes 1 positional argument but 2 were given
[2023-12-29 00:30:52,609.609] INFO [3070088768] - Shutting down
[2023-12-29 00:30:52,711.711] INFO [3070088768] - Waiting for application shutdown.
[2023-12-29 00:30:52,715.715] INFO [3070088768] - Application shutdown complete.
[2023-12-29 00:30:52,717.717] INFO [3070088768] - Finished server process [13248]
[2023-12-29 00:31:24,177.177] INFO [3069265472] - Started server process [13929]
[2023-12-29 00:31:24,181.181] INFO [3069265472] - Waiting for application startup.
[2023-12-29 00:31:24,185.185] INFO [3069265472] - Application startup complete.
[2023-12-29 00:31:24,220.220] INFO [3069265472] - Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[2023-12-29 00:33:49,141.141] INFO [3069265472] - 192.168.1.74:49960 - "GET /status HTTP/1.1" 200
[2023-12-29 00:34:20,121.121] INFO [3069265472] - 192.168.1.74:49960 - "GET /available HTTP/1.1" 200
[2023-12-29 00:34:41,261.261] INFO [3069265472] - 192.168.1.74:50117 - "GET /in_meeting HTTP/1.1" 200
[2023-12-29 00:35:01,729.729] INFO [3069265472] - 192.168.1.74:50196 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:06,674.674] INFO [3069265472] - 192.168.1.74:50196 - "GET /reset HTTP/1.1" 200
[2023-12-29 00:35:08,910.910] INFO [3069265472] - 192.168.1.74:50196 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:26,546.546] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:27,326.326] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:28,011.011] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:28,812.812] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:29,396.396] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:30,085.085] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:30,763.763] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:31,439.439] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:32,166.166] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:32,765.765] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:33,368.368] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:34,413.413] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:35,107.107] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:35,969.969] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:36,718.718] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:37,926.926] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:39,090.090] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:40,332.332] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:41,236.236] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:42,266.266] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:43,151.151] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:44,369.369] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:45,328.328] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:46,351.351] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:47,414.414] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:48,339.339] INFO [3069265472] - 192.168.1.74:50196 - "GET /available HTTP/1.1" 200
[2023-12-29 00:35:48,361.361] INFO [3069265472] - 192.168.1.74:50246 - "GET /reset HTTP/1.1" 200
[2023-12-29 00:35:48,366.366] INFO [3069265472] - 192.168.1.74:50254 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:50,786.786] INFO [3069265472] - 192.168.1.74:50246 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:52,151.151] INFO [3069265472] - 192.168.1.74:50246 - "GET /status HTTP/1.1" 200
[2023-12-29 00:35:58,089.089] INFO [3069265472] - Shutting down
[2023-12-29 00:35:58,193.193] INFO [3069265472] - Waiting for application shutdown.
[2023-12-29 00:35:58,196.196] INFO [3069265472] - Application shutdown complete.
[2023-12-29 00:35:58,198.198] INFO [3069265472] - Finished server process [13929]
[2023-12-29 00:36:28,825.825] INFO [3069175360] - Started server process [14463]
[2023-12-29 00:36:28,829.829] INFO [3069175360] - Waiting for application startup.
[2023-12-29 00:36:28,832.832] INFO [3069175360] - Application startup complete.
[2023-12-29 00:36:28,868.868] INFO [3069175360] - Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[2023-12-29 00:36:29,353.353] INFO [3069175360] - 192.168.1.74:50422 - "GET /status HTTP/1.1" 200
[2023-12-29 00:37:16,393.393] INFO [3069175360] - 192.168.1.74:50422 - "GET /available HTTP/1.1" 200
[2023-12-29 00:37:28,847.847] INFO [3069175360] - 192.168.1.74:50441 - "GET /in_meeting HTTP/1.1" 200
[2023-12-29 00:39:43,301.301] INFO [3069175360] - Shutting down
[2023-12-29 00:39:43,405.405] INFO [3069175360] - Waiting for application shutdown.
[2023-12-29 00:39:43,408.408] INFO [3069175360] - Application shutdown complete.
[2023-12-29 00:39:43,410.410] INFO [3069175360] - Finished server process [14463]
[2023-12-29 01:01:52,980.980] INFO [3070023232] - Started server process [1283]
[2023-12-29 01:01:52,998.998] INFO [3070023232] - Waiting for application startup.
[2023-12-29 01:01:53,002.002] INFO [3070023232] - Application startup complete.
[2023-12-29 01:01:53,149.149] INFO [3070023232] - Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[2023-12-29 01:02:36,523.523] INFO [3069249088] - Started server process [1443]
[2023-12-29 01:02:36,557.557] INFO [3069249088] - Waiting for application startup.
[2023-12-29 01:02:36,560.560] INFO [3069249088] - Application startup complete.
[2023-12-29 01:02:36,717.717] ERROR [3069249088] - [Errno 98] error while attempting to bind on address ('0.0.0.0', 80): address already in use
[2023-12-29 01:02:36,719.719] INFO [3069249088] - Waiting for application shutdown.
[2023-12-29 01:02:36,721.721] INFO [3069249088] - Application shutdown complete.
[2023-12-29 01:03:08,857.857] INFO [3070023232] - 192.168.1.74:52990 - "GET /status HTTP/1.1" 200
[2023-12-29 01:03:37,120.120] INFO [3070023232] - 192.168.1.74:52990 - "GET /available HTTP/1.1" 200
[2023-12-29 01:32:41,825.825] INFO [3069916736] - Started server process [5228]
[2023-12-29 01:32:41,829.829] INFO [3069916736] - Waiting for application startup.
[2023-12-29 01:32:41,832.832] INFO [3069916736] - Application startup complete.
[2023-12-29 01:32:41,867.867] INFO [3069916736] - Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[2023-12-29 01:33:33,025.025] INFO [3069916736] - 192.168.1.74:63533 - "GET /available HTTP/1.1" 200
[2023-12-29 01:34:57,154.154] INFO [3069916736] - 192.168.1.74:63741 - "GET /in_meeting HTTP/1.1" 200
[2023-12-29 01:36:31,778.778] INFO [3069916736] - Shutting down
[2023-12-29 01:36:31,881.881] INFO [3069916736] - Waiting for application shutdown.
[2023-12-29 01:36:31,885.885] INFO [3069916736] - Application shutdown complete.
[2023-12-29 01:36:31,887.887] INFO [3069916736] - Finished server process [5228]
                                                                                                                                                                                                                                                                                                                                                                [2023-12-29 01:41:42,734.734] INFO [3069212224] - Started server process [558]
[2023-12-29 01:41:42,741.741] INFO [3069212224] - Waiting for application startup.
[2023-12-29 01:41:42,745.745] INFO [3069212224] - Application startup complete.
[2023-12-29 01:41:42,825.825] INFO [3069212224] - Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[2023-12-29 01:42:59,614.614] INFO [3069212224] - 192.168.1.74:65454 - "GET /status HTTP/1.1" 200
[2023-12-29 01:52:26,544.544] WARNING [3069212224] - Invalid HTTP request received.
[2023-12-29 01:53:33,009.009] INFO [3069212224] - 192.168.1.74:51026 - "GET /status HTTP/1.1" 200
[2023-12-29 01:56:13,697.697] INFO [3069212224] - 192.168.1.41:52122 - "GET /available HTTP/1.1" 500
[2023-12-29 01:56:13,700.700] ERROR [3069212224] - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 70, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/dist-packages/starlette/concurrency.py", line 35, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/an63l/app/main.py", line 52, in available
    while get_status() == "WRITING":
  File "/home/an63l/app/main.py", line 95, in get_status
    for item in db:
  File "/usr/local/lib/python3.9/dist-packages/tinydb/table.py", line 655, in __iter__
    for doc_id, doc in self._read_table().items():
  File "/usr/local/lib/python3.9/dist-packages/tinydb/table.py", line 704, in _read_table
    tables = self._storage.read()
  File "/usr/local/lib/python3.9/dist-packages/tinydb/storages.py", line 136, in read
    return json.load(self._handle)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2023-12-29 01:56:14,550.550] INFO [3069212224] - 192.168.1.41:36068 - "GET /in_meeting HTTP/1.1" 200
[2023-12-29 01:56:14,566.566] INFO [3069212224] - 192.168.1.41:52138 - "GET /reset HTTP/1.1" 200
[2023-12-29 01:57:17,416.416] INFO [3069212224] - 192.168.1.41:33874 - "GET /available HTTP/1.1" 200
[2023-12-29 01:57:31,038.038] INFO [3069212224] - 192.168.1.41:57866 - "GET /in_meeting HTTP/1.1" 200
[2023-12-29 01:57:31,056.056] INFO [3069212224] - 192.168.1.41:33874 - "GET /reset HTTP/1.1" 200
[2023-12-29 02:33:55,587.587] INFO [3069212224] - 192.168.1.74:65368 - "GET /status HTTP/1.1" 200
[2023-12-29 02:56:58,017.017] INFO [3069212224] - 192.168.1.41:40994 - "GET /reset HTTP/1.1" 200
[2023-12-29 02:57:13,295.295] INFO [3069212224] - 192.168.1.41:40994 - "GET /in_meeting HTTP/1.1" 200
